repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent, '4']

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-crlf

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix]

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4', --trailing-comma]

-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
    -   id: hadolint
        files: .*Dockerfile[^.]*(\.[^.]*)?$

-   repo: local
    hooks:
    -   id: uv-pip-compile
        name: Check requirements files
        entry: uv pip compile requirements.in.txt -o requirements.txt -q
        require_serial: true
        language: python
        additional_dependencies: [uv >= 0.1.21]
        files: requirements.in.txt
