repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.24
    hooks:
      - id: uv-lock

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']
      - id: pretty-format-toml
        args: [--autofix, --indent, '4', --trailing-comma]

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        files: .*Dockerfile[^.]*(\.[^.]*)?$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.101.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.38.0
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        args: [--check-metaschema]
        files: ^renovate.json$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        additional_dependencies:
          - github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.14.2
    hooks:
      - id: zizmor
