version: '3.9'

services:
    tg_forwarder:
        env_file: .env
        image: tg_forwarder:latest
        build:
            # Sorry for this - deployed as a "secondary" app on a server
            # where main service has own compose file.
            context: ../gmail_telegram
            dockerfile: Dockerfile
        networks:
        -   djangonetwork
        restart: unless-stopped
        volumes:
        -   files_volume:/app/.temp_files

networks:
    djangonetwork:
        driver: bridge

volumes:
    files_volume:
