services:
    ddb:
        image: amazon/dynamodb-local:latest
        working_dir: /home/dynamodblocal
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
        ports:
        -   8181:8000
        user: root
        volumes:
        -   ddb:/home/dynamodblocal/data

volumes:
    ddb:
