services:
    tg_forwarder:
        env_file: .env
        build:
            context: .
        restart: unless-stopped

    ddb:
        image: amazon/dynamodb-local:latest
        working_dir: /home/dynamodblocal
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
        user: root
        volumes:
        -   ddb:/home/dynamodblocal/data

volumes:
    ddb:
