name: Lint and Test

permissions:
    contents: read

on:
    pull_request:
        branches: [master]

jobs:
    pre-commit:
        name: Pre-commit hooks
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4

        -   uses: actions/setup-python@v5
            with:
                python-version: '3.12'
        -   uses: hashicorp/setup-terraform@v3
        -   uses: terraform-linters/setup-tflint@v4
            name: Setup TFLint
            with:
                tflint_version: latest
        -   name: Init TFLint
            run: tflint --init
            env:
                # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
                GITHUB_TOKEN: ${{ github.token }}

        -   uses: pre-commit/action@v3.0.1
            with:
                extra_args: --all-files --show-diff-on-failure

    check-build:
        name: Check docker build
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4

        -   uses: docker/build-push-action@v6
            with:
                tags: dev
                target: deploy
                load: true
                cache-from: type=gha
                cache-to: type=gha,mode=max
